version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:us-east-2:008875796240:task-definition/Task-Defination-BG-codecommit:1"
       LoadBalancerInfo:
         ContainerName: "BluegreenContaine"
         ContainerPort: 8080
